language: scala
sudo: true

services: docker

jobs:
  include:
  - stage: build
    script: source sbin/functions.sh; init-docker; build
    if: NOT branch = master OR type = pull_request AND NOT tag IS blank
#
#  - stage: build
#    scala: 2.10.7
#    script: source sbin/functions.sh; init-docker; build
#    if: NOT branch = master OR type = pull_request AND NOT tag =~ ^tt[1-9]

## Publish
#  - stage: publish
#    script: source sbin/functions.sh; init-docker; publish_snapshot
#    scala: 2.11.12
#    if: branch = master AND tag IS blank AND type = push
#
#  - stage: publish
#    script: source sbin/functions.sh; init-docker; publish_snapshot
#    scala: 2.10.7
#    if: branch = master AND tag IS blank AND type = push

# Release
  - stage: publish
    language: bash
    script: source sbin/functions.sh; release
    if: tag =~ ^tt[1-9]

#
#  - stage: publish
#    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
#    scala: 2.11.12
#    env: SPARK_VERSION=2.2.1
#    script: source sbin/functions.sh; publish
#
#  - stage: publish
#    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
#    scala: 2.10.7
#    env: SPARK_VERSION=2.2.1
#    script: source sbin/functions.sh; publish
#
#  - stage: publish
#    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
#    scala: 2.11.12
#    env: SPARK_VERSION=2.2.0
#    script: source sbin/functions.sh; publish
#
#  - stage: publish
#    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
#    scala: 2.10.7
#    env: SPARK_VERSION=2.2.0
#    script: source sbin/functions.sh; publish
