language: scala
sudo: true

services: docker

jobs:
  include:
  - stage: build
    scala: 2.11.12
    env: SPARK_VERSION=2.2.1
    script: source sbin/functions.sh; build

  - stage: build
    scala: 2.10.7
    env: SPARK_VERSION=2.2.1
    script: source sbin/functions.sh; build

  - stage: build
    scala: 2.11.12
    env: SPARK_VERSION=2.2.0
    script: source sbin/functions.sh; build

  - stage: build
    scala: 2.10.7
    env: SPARK_VERSION=2.2.0
    script: source sbin/functions.sh; build

# Publish
  - stage: publish
    if: branch = master
    scala: 2.11.12
    env: SPARK_VERSION=2.2.1
    script: source sbin/functions.sh; publish

  - stage: publish
    if: branch = master
    scala: 2.10.7
    env: SPARK_VERSION=2.2.1
    script: source sbin/functions.sh; publish

  - stage: publish
    if: branch = master
    scala: 2.11.12
    env: SPARK_VERSION=2.2.0
    script: source sbin/functions.sh; publish

  - stage: publish
    if: branch = master
    scala: 2.10.7
    env: SPARK_VERSION=2.2.0
    script: source sbin/functions.sh; publish


stages:
  - build
  - publish

