language: scala
sudo: true

services: docker

jobs:
  include:
  - stage: build
    scala: 2.11.12
    env: SPARK_VERSION=2.3.0
    script: source sbin/functions.sh; build

  - stage: build
    scala: 2.11.12
    env: SPARK_VERSION=2.2.1
    script: source sbin/functions.sh; build

  - stage: build
    scala: 2.10.7
    env: SPARK_VERSION=2.2.1
    script: source sbin/functions.sh; build

  - stage: build
    scala: 2.11.12
    env: SPARK_VERSION=2.2.0
    script: source sbin/functions.sh; build

  - stage: build
    scala: 2.10.7
    env: SPARK_VERSION=2.2.0
    script: source sbin/functions.sh; build

# Publish
  - stage: publish
    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
    scala: 2.11.12
    env: SPARK_VERSION=2.3.0

  - stage: publish
    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
    scala: 2.11.12
    env: SPARK_VERSION=2.2.1
    script: source sbin/functions.sh; publish

  - stage: publish
    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
    scala: 2.10.7
    env: SPARK_VERSION=2.2.1
    script: source sbin/functions.sh; publish

  - stage: publish
    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
    scala: 2.11.12
    env: SPARK_VERSION=2.2.0
    script: source sbin/functions.sh; publish

  - stage: publish
    if: NOT type IN (pull_request) AND (branch = master OR tag =~ ^v[1-9])
    scala: 2.10.7
    env: SPARK_VERSION=2.2.0
    script: source sbin/functions.sh; publish

stages:
  - build
  - publish

